// export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const FORM_ROUTE = '/form'
export const REGISTRATION_ROUTE = '/registration'
export const PROJECT_ROUTE = '/project'
export const CLIENT_ROUTE = '/client'
